# this file contains all flags and project global variables
SERVER_PING = 900
SERVER_CONNECT_OK = 901
SERVER_LOGIN_OK = 902
SERVER_OK = 903

CLIENT_IS_ONLINE = 800
CLIENT_SIGN_IN_REQUEST = 801
CLIENT_FETCH_ONLINE_USERS_REQUEST = 802
CLIENT_CHECK_SERVER_AVAILABILITY = 803
CLIENT_TEMPORARILY_LOGIN_REQUEST = 804
CLIENT_LOG_OFF = 805

ILLEGAL_REQUEST = 700